apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    azure.workload.identity/client-id: 2904629d-f54a-461c-9d8b-06c028d5e12c
  labels:
    azure.workload.identity/use: "true"