apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    azure.workload.identity/client-id: 2218e05e-2eb1-46da-9535-dcbe4ada692a
  labels:
    azure.workload.identity/use: "true"