apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    azure.workload.identity/client-id: 8245a0a5-6b4f-48af-9a7c-c99b1db3cde3
    azure.workload.identity/tenant-id: efcfc581-a0bd-4c8c-a3c2-6c3cae8e5800
    azure.workload.identity/service-account-token-expiration: 3600
  labels:
    azure.workload.identity/use: "true"