apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    azure.workload.identity/client-id: 16ff4cec-3e1f-493d-972c-c8dfaaf1a7c1
    azure.workload.identity/tenant-id: efcfc581-a0bd-4c8c-a3c2-6c3cae8e5800
  labels:
    azure.workload.identity/use: "true"