apiVersion: v1
kind: Secret
metadata:
    name: sample-secret
    namespace: sops-workload-identity
type: Opaque
stringData:
    sops_encrypted_secret: ENC[AES256_GCM,data:HRlEXmlnX+05/iB8qOmpXTQdaA==,iv:KEMWL7FO1/URi6CBrTCGEFvwUqkgDZudEIQ52gYFLZU=,tag:Z5GHwddez+7f0Y/fo0tPPg==,type:str]
sops:
    azure_kv:
        - vault_url: https://my-kv-55qgmoueto4pc.vault.azure.net
          name: encryption-key
          version: 3843da5f08b047a1b78858233381ba21
          created_at: "2025-05-07T08:58:18Z"
          enc: d4y1YLa5dZiCRfUN1d0EcEt-BdcoSTnAKmykCLrWYdMY4v3d2UawQEb_NLXwSZmrBycOW7FA4tN9-Yb1mecevwGtHPMZacrXMl3P0RkjBlXQwY807-COvv3MrDTrCgIJCMcDn5y_Fbv0_vOO47hTssRzu3QyJOKesva4vBa6Ca7W6DbxoESmqhhQSRuw21rdeJVUe5z75NOExtd-AAbCSCTjuE936626b8FH4odDfXQ1dKx5aTiVRM-Zo2BDzt_QjMKCqwxg0VjXDfeK80HqyLcVK0l_EOLEyD65Gj6L7j9mW4aYA0lNErP5pKL-63XW719_KSRp8BL_UsD0XTjenQ
    lastmodified: "2025-05-07T08:58:20Z"
    mac: ENC[AES256_GCM,data:T+LKNYf/JT9c6HK7XqKT4K17NTbQnRR50kJQvUnfOjnCkpHcIVQxLKWac+Awb8poQy4p42wlFkYdFDB1G6CttK9nc3kArrC+6V+5tPIJO6d3vRh/xCkGEI198flVRGHvW4w9fSj45lCYtd73gA4jxmORRVTVhcnC453y/yH7oYE=,iv:jR8yqA8zC9cSFEbypF5flXkIFCsDOdXn1/EoqVXDwL4=,tag:3+Du4ZXM/7r8FsAo2OVryw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
