apiVersion: v1
kind: Secret
metadata:
    name: sample-secret
    namespace: sops-workload-identity
type: Opaque
stringData:
    sops_encrypted_secret: ENC[AES256_GCM,data:52MPrvm0Ig/NeJW+aupr2AlIvA==,iv:BAZ7GtiXdDRV2Gw6g8lEOSKKwCAVeci843GSCaMmqDg=,tag:6XGEPMhnkF8Ah9X01NRtlw==,type:str]
sops:
    azure_kv:
        - vault_url: https://my-kv-55qgmoueto4pc.vault.azure.net
          name: encryption-key
          version: 75e2cbf9365248d89ddfa29fbf5c8254
          created_at: "2025-05-07T10:14:37Z"
          enc: DvPytzuNeyy8epSBpfBnOpLKpfDzuYT5CCJ_mQxpU3SV2EL6eDxPIQtwUCfH-WwqnTEO5KHd6qConHNcnp-agpHeJzbdt7hFKEQreWWr3VFfXhhzZToUldzElgPSoCsdS-DyRjRJaOksGaqCuoCS-42FABS8Ml-5G2425bsiJoVrbrzgVDOCzBVhlkbudPC31znUn24d1qOA8sxn_KKgteQFLS1Ki51K1xwckrQDLlhOn0j9KwQpI8JIp9oeQ9k5M2Gs0iQTQKrSAiRK6kj8KZaspkqsEbNix7RE9zIAgM8QSTtxMXazUPsVzWj72pcnB27-7NdDLZIe9IIAFjpP7Q
    lastmodified: "2025-05-07T10:14:39Z"
    mac: ENC[AES256_GCM,data:9WXOaI8gCLU3E0nn8IJHHyXni8FxSIIqSuAuD8GvSRpoiq8yYXrs3o+5/l9ES4qtkQ5/dQ57ESUiAGNxz9padAFROmydB+B8FRLH8ksRdti1x1LA0op5dSl7UWnKAMH1loo6DWf9uPu1WiKWAfOMYavHbCV+Rw692oL+bcbnoBs=,iv:hup+Dwt8zDzQ00J4ITJFMUKGBTAKPaO9VnN32M7bC00=,tag:Z3cI6XD6y+nteS1sNctyXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
