apiVersion: v1
kind: Secret
metadata:
    name: sample-secret
    namespace: sops-workload-identity
type: Opaque
stringData:
    sops_encrypted_secret: ENC[AES256_GCM,data:cLL7jvTxQK/SSuVljeGr+xfaSA==,iv:ClZMjmdAbhH0nr5rYq8GA95BmX2ieykrbNmbm4MNRlI=,tag:CRPyEDe7+gdcztvE0PrARQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://my-kv-55qgmoueto4pc.vault.azure.net
          name: encryption-key
          version: 105c8824fd2343c4a94fed4021cdd67c
          created_at: "2023-11-01T09:36:29Z"
          enc: nsWbm_KIpyGRXbbcSddkNDYyEJQTM8XhZpCO4mhPNP7WHHbl0gYREn6nJH0tonQvyPLCHSIUXb1oY8lrvX4ZHl2oazSU5DRO2jffdaLORzSP5gAloRW2ZhTWZ_qoa5xaWOhT_lO2Cg2xX-RDV5Hji7kmFC3O30HMLb2GGNm7bFkpmR_77xyeumMTu2wwV5J-itgeQVD-aZkjW76dvBBDto2bWkTNTJjXonTu4iIqUTsu4GlhLUt3y48q-iS6YrSXyt0zSEIdA3hRMllw3241ce8Gl_tVoq3yXjXUDXj5F_u3-KyFRffjKImwU6Oid8G6uDcezUTgAJYxaGKSXOJG7Q
    hc_vault: []
    age: []
    lastmodified: "2023-11-01T09:36:35Z"
    mac: ENC[AES256_GCM,data:HDOwtpwpJNOjgI1fz7T6VRjhcB2iZAaQwaiqTkxb7zid2xgzkxsbsR1U/YfBBDc1vooelnZLiOgdM6S80aG6DgO6r8LKxWRwrbQ3ZJNg0vz9JnRNON0ULimr96Qgs1UCsROoZw2It7zcc42zq+c7k7lsWfTmaOTIhWAirNqaJek=,iv:hXard5D0VO1izxvKY/6ONJyPzh5+IeWVssPUzP9ueN0=,tag:hFWsxKi0e/p/ZVw/NR5B2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
