apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

# patches:
#   - path: patches/kustomize-controller-deployment.yaml
#   - path: patches/kustomize-controller-service-account.yaml
